version: '3.7'
services:
  api:
    image: node:16
    tty: true
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm run start:dev
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7.29
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: common
      MYSQL_PASSWORD: password
